### ISSUE TITLE
XML exporter

### ISSUE THREAD

**Issue by poldi2015** [itsallcode/openfasttrace#260]
Openfasttrace provides basic reports for commandline and HTML. In many projects these reports do not cover all requirements (e.g. customer specific style, statistics, search, sort, filter facabilties etc.). Therefore openfastrace should be able to report a computer processable report with all imported requirements, relevant information of covering requirements per requirement, shallow and transient coverage status per requirement, some statistics.

**Comment by wreggyl** [comment]
SpecObjes are already supported for single reqs/spec items, Is ReqIF as the whole XML a valid option in your opinion? I am really new to ReqIF and OFT, so sorry for this question?

**Comment by redcatbear** [comment]
The XML export in the SpecObject format is very close to OFT's internal representation. Unlike RIF (ReqIF's predecessor), OFT intentionally uses a predefined, restricted set of attributes. We focus more on speed and covering the 80% case instead of maximum flexibility. It is probably possible to losslessly export OFT requirements to ReqIF, but I doubt the other direction would be lossless.

The SpecObject format was established in the Automotive Software industry and is a format that grew over the years. OFT was made with the goal to be able to ingest and produce SpecObject files to act as a drop-in replacement for SpecObject-capable toolchains.

**Comment by kaklakariada** [comment]
@redcatbear what do you think about providing an XML schema for OFT's SpecObject format? This might help consumers processing it.
